openapi: 3.0.0
info:
  title: 'MLS API'
  version: 1.0.0
paths:
  /api/tele-app/properties:
    get:
      tags:
        - Properties
      summary: 'Get list of property'
      description: 'Returns list of property'
      operationId: index
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                properties:
                  properties:
                    type: array
                    items:
                      $ref: '#/components/schemas/Property'
                type: object
  '/api/tele-app/properties/{id}':
    get:
      tags:
        - Properties
      summary: 'Get property by id'
      operationId: show
      parameters:
        -
          name: id
          in: path
          description: 'Property Id'
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        404:
          description: 'Property not found'
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    example: 'Property not found'
                type: object
    post:
      tags:
        - Properties
      summary: 'Update property'
      operationId: update
      parameters:
        -
          name: id
          in: path
          description: 'Property Id'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdatePropertyRequest'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        404:
          description: 'Property not found'
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    example: 'Property not found'
                type: object
components:
  schemas:
    UpdatePropertyRequest:
      properties:
        title:
          type: string
          example: 'Rumah dijual di daerah pasteur'
        address:
          type: string
          example: 'Jl. Pendidikan No. 1'
        description:
          type: string
          example: 'Rumah bagus'
        price:
          type: integer
          example: 100000
        lotSize:
          type: integer
          example: 1000
        buildingSize:
          type: integer
          example: 2000
        carCount:
          type: integer
          example: 4
        bedroomCount:
          type: integer
          example: 3
        bathroomCount:
          type: integer
          example: 2
        floorCount:
          type: integer
          example: 2
        facing:
          type: string
          example: Utara
        ownership:
          type: string
          example: SHM
        city:
          type: string
          example: Bandung
        pictureUrls:
          type: array
          items:
            oneOf:
              -
                type: string
                format: binary
                example: \x00\x00\x00\x04\x00\x00\x00\x04
              -
                type: string
                format: url
                example: 'https://example.com/image.jpg'
        coordinate:
          properties:
            latitude:
              type: integer
            longitude:
              type: integer
          type: object
        contacts:
          properties:
            name:
              type: string
            profilePictureURL:
              type: string
            phoneNumber:
              type: string
            sourceURL:
              type: string
            provider:
              type: string
          type: object
        isPrivate:
          type: boolean
          example: false
      type: object
    Property:
      properties:
        id:
          type: string
        title:
          type: string
        address:
          type: string
        description:
          type: string
        price:
          type: integer
        lotSize:
          type: integer
        buildingSize:
          type: integer
        carCount:
          type: integer
        bedroomCount:
          type: integer
        bathroomCount:
          type: integer
        floorCount:
          type: integer
        facing:
          type: string
        ownership:
          type: string
        city:
          type: string
        pictureUrls:
          type: array
          items:
            type: string
            format: uri
            example: 'https://example.com/image.jpg'
        coordinate:
          properties:
            latitude:
              type: integer
            longitude:
              type: integer
          type: object
        contacts:
          properties:
            name:
              type: string
            profilePictureURL:
              type: string
            phoneNumber:
              type: string
            sourceURL:
              type: string
            provider:
              type: string
          type: object
        userCanEdit:
          type: boolean
        isPrivate:
          type: boolean
      type: object
