image: php:8.2-fpm-bullseye

pipelines:
  branches:
    main:
      - step:
          name: Build JS
          caches:
            - composer
            - node
          script:
            # We actually just need to build the JS to public/build, but the JS build needs a JS package ziggy-js
            # that is installed in composer vendor. So we also have to do composer install although this vendor dir
            # will not get uploaded to app engine at deploy step.
            - apt-get update
            - apt-get install -y zip # needed for one of composer package
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.6.5
            - composer install --no-dev
            - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            - apt-get install -y nodejs
            - npm install
            - npm run build
          artifacts:
            - public/build/**
      - step:
          name: Deploy to GAE dev environment
          script:
            # Populate app.yaml from the template of dev environment.
            # Variables are taken from Bitbucket's Repository Variables.
            - cp app.yaml.dev app.yaml
            - cp additional-supervisord.conf.template additional-supervisord.conf # for queue worker
            - sed -i 's|\<\(APP_KEY:\).*|\1 '"$DEV_APP_KEY"'|' app.yaml
            - sed -i 's|\<\(CHATGPT_KEY:\).*|\1 '"$DEV_OPENAI_KEY"'|' app.yaml
            - sed -i 's|\<\(MONGODB_SRV:\).*|\1 '"$DEV_MONGODB_SRV"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_BACKDOOR_KEY:\).*|\1 '"$DEV_TELEGRAM_BACKDOOR_KEY"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_BOT_TOKEN:\).*|\1 '"$DEV_TELEGRAM_BOT_TOKEN"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_WEBHOOK_SECRET:\).*|\1 '"$DEV_TELEGRAM_WEBHOOK_SECRET"'|' app.yaml
            - sed -i 's|\<\(GOOGLE_CLIENT_ID:\).*|\1 '"$GOOGLE_CLIENT_ID"'|' app.yaml
            - sed -i 's|\<\(GOOGLE_CLIENT_SECRET:\).*|\1 '"$GOOGLE_CLIENT_SECRET"'|' app.yaml
            - pipe: atlassian/google-app-engine-deploy:1.5.0
              variables:
                KEY_FILE: $KEY_FILE
                PROJECT: daftar-properti-dev
                STOP_PREVIOUS_VERSION: "true"
