image: php:8.2-fpm-bullseye

pipelines:
  branches:
    main:
      - step:
          name: Deploy to GAE dev environment
          script:
            # Populate app.yaml from the template of dev environment.
            # Variables are taken from Bitbucket's Repository Variables.
            - cp app.yaml.dev app.yaml
            - sed -i 's|\<\(APP_KEY:\).*|\1 '"$DEV_APP_KEY"'|' app.yaml
            - sed -i 's|\<\(CHATGPT_KEY:\).*|\1 '"$DEV_OPENAI_KEY"'|' app.yaml
            - sed -i 's|\<\(MONGODB_SRV:\).*|\1 '"$DEV_MONGODB_SRV"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_BACKDOOR_KEY:\).*|\1 '"$DEV_TELEGRAM_BACKDOOR_KEY"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_BOT_TOKEN:\).*|\1 '"$DEV_TELEGRAM_BOT_TOKEN"'|' app.yaml
            - sed -i 's|\<\(TELEGRAM_WEBHOOK_SECRET:\).*|\1 '"$DEV_TELEGRAM_WEBHOOK_SECRET"'|' app.yaml
            - pipe: atlassian/google-app-engine-deploy:1.5.0
              variables:
                KEY_FILE: $KEY_FILE
                PROJECT: daftar-properti-dev
