version: '3.8'
services:
  test-mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: testpassword
