# Container for daftarproperti feature tests.

# Pin to 8.3.13 due to bug in 8.3.14 about gmp_pow.
FROM php:8.3.13-cli-bookworm

RUN apt-get update
RUN apt-get install -y git zip unzip curl

# Needs SSL library for mongodb
RUN apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev
RUN pecl install mongodb && docker-php-ext-enable mongodb

# pcntl is required for pail package's dependencies
RUN docker-php-ext-configure pcntl --enable-pcntl && docker-php-ext-install pcntl

# Needs `nc` to probe mongodb readiness
RUN apt-get install -y netcat-traditional

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.6.5

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

# Install Node.js and npm
RUN apt-get update && apt-get install -y nodejs

RUN apt-get install -y libgmp-dev && docker-php-ext-install gmp

WORKDIR /usr/src/daftarproperti
COPY ./ ./
